OpenEnded Task Using ANN Model (Train Set)

In [ ]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import load_model
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import warnings
warnings.filterwarnings('ignore')

In [2]:
test_data = pd.read_csv("mnist_test.csv")  # Replace with your actual file path

# Check first few rows to verify structure
test_data.head()

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   783  label  
0    0      7  
1    0      2  
2    0      1  
3    0      0  
4    0      4  

[5 rows x 785 columns]

In [28]:
# Split features (X_test) and labels (y_test)
X_test = test_data.iloc[:, :-1].values  # Pixel values
y_test = test_data.iloc[:, -1].values   # Labels (digits 0-9)

In [30]:
X_test = X_test.astype('float32') / 255.0

In [32]:
model = load_model("mnist_ann_model.h5")  # Replace with your model file path

In [34]:
predictions = model.predict(X_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


In [36]:
predicted_labels = np.argmax(predictions, axis=1)

In [38]:
print("First 10 Predicted Labels:", predicted_labels[:10])
print("First 10 Actual Labels:   ", y_test[:10])

First 10 Predicted Labels: [7 2 1 0 4 1 4 9 5 9]
First 10 Actual Labels:    [7 2 1 0 4 1 4 9 5 9]


In [40]:
accuracy = accuracy_score(y_test, predicted_labels)
print(f"\nTest Accuracy: {accuracy:.4f}")


Test Accuracy: 0.9783


In [42]:
print("\nClassification Report:")
print(classification_report(y_test, predicted_labels))


Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.99      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.98      0.97      0.98      1032
           3       0.97      0.99      0.98      1010
           4       0.98      0.98      0.98       982
           5       0.98      0.97      0.98       892
           6       0.98      0.99      0.98       958
           7       0.97      0.98      0.97      1028
           8       0.98      0.96      0.97       974
           9       0.98      0.96      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000



In [48]:
# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, predicted_labels))


Confusion Matrix:
[[ 966    1    1    1    0    1    6    2    2    0]
 [   0 1126    5    0    0    0    2    0    2    0]
 [   4    0 1006    3    4    0    3    9    3    0]
 [   1    0    2  996    0    1    0    4    2    4]
 [   1    0    1    0  962    0    5    4    1    8]
 [   2    0    0   12    1  869    3    1    2    2]
 [   2    2    0    1    3    4  946    0    0    0]
 [   1    4   11    3    0    0    0 1004    2    3]
 [   5    0    5    5    5    7    4    4  935    4]
 [   2    3    0    8   11    2    0    7    3  973]]
